# Generated by Django 4.0.6 on 2022-08-03 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='date',
            new_name='intention',
        ),
        migrations.AddField(
            model_name='post',
            name='location',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='price',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
